### ISSUE TITLE
输入python3 darkangel.py --scan-new-domain后报错

### ISSUE THREAD

**Issue by 521225** [Bywalks/DarkAngel#1]
Traceback (most recent call last):
  File "/root/DarkAngel-main/DarkAngel-main/darkangel.py", line 44, in <module>
    from subdomain.oneforall.subdomain_run import SubDomain
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/subdomain_run.py", line 10, in <module>
    from subdomain.oneforall.oneforall import OneForAll as OneForAll
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/oneforall.py", line 14, in <module>
    import export
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/export.py", line 13, in <module>
    from common import utils
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/common/utils.py", line 21, in <module>
    from common.database import Database
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/common/database.py", line 8, in <module>
    from config.log import logger
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/config/__init__.py", line 17, in <module>
    settings = Settings()
  File "/root/DarkAngel-main/DarkAngel-main/subdomain/oneforall/config/__init__.py", line 12, in __init__
    setting = importlib.import_module(setting_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'config.setting'

搞了好久...网上找不到解决办法

**Comment by Bywalks** [comment]
重新拉取一下源代码，代码已更新。

**Comment by Bywalks** [comment]
已解决

![image](https://user-images.githubusercontent.com/32921125/208097094-c86b78e7-96e3-484f-af19-cccd19d5b45e.png)
