### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by ciscochao** [Bywalks/DarkAngel#15]
哈喽，按照说明拉取容器和程序并配置好config.ini，但在容器中运行python3 darkangel.py -h时报错，信息如下请问需要怎么解决

[root@f2127e556ec0 DarkAngel]# python3 darkangel.py -h
Traceback (most recent call last):
  File "darkangel.py", line 32, in <module>
    from vulscan.xray_scan import *
  File "/root/DarkAngel/vulscan/xray_scan.py", line 27, in <module>
    from vcommon.vuln_manage import VulnManager
  File "/root/DarkAngel/vcommon/vuln_manage.py", line 18, in <module>
    from vconfig.config import *
  File "/root/DarkAngel/vconfig/config.py", line 30, in <module>
    H1_COOKIE = config.get('h1', "h1_cookie")
  File "/usr/local/python3/lib/python3.7/configparser.py", line 799, in get
    d)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%3D%3D--563881120fc1d004c05996f07e528e84f836efd3'

**Comment by Bywalks** [comment]
H1_cookie填错了，看一下这个，https://github.com/Bywalks/DarkAngel/issues/5

**Comment by ciscochao** [comment]
> H1_cookie填错了，看一下这个，#5

Nice，确实是编码问题，改成==之后正常运行了，非常感谢！
